#!/bin/bash
#
#

file=`dirname $0`/core/include/ds/version.h
pom=`dirname $0`/java/pom.xml

perl -i -p -e 's/(.*BUILD_VERSION)[[:space:]]+=[[:space:]]+([[:digit:]]+);/"$1 = " . ($2 + 1) . ";"/e' $file            

major=`cat $file | grep MAJOR_VERSION | sed -e 's/[^0-9]//g'`
minor=`cat $file | grep MINOR_VERSION | sed -e 's/[^0-9]//g'`
build=`cat $file | grep BUILD_VERSION | sed -e 's/[^0-9]//g'`

/bin/sed -i -e "/<artifactId>ds<\/artifactId>/, +1 s/<version>.*<\/version>/<version>$major.$minor.$build<\/version>/" $pom

cat $file
cat $pom| grep version

