IF (NOT DEFINED MATLAB_ROOT)
  MESSAGE(FATAL_ERROR "*** MATLAB_ROOT is not set ***")
ENDIF (NOT DEFINED MATLAB_ROOT)

SET(MEX_PLATFORM glnxa64)
SET(MEX ${MATLAB_ROOT}/bin/mex)
EXECUTE_PROCESS(COMMAND ${MATLAB_ROOT}/bin/mexext OUTPUT_VARIABLE MEX_SUFFIX OUTPUT_STRIP_TRAILING_WHITESPACE)

message("[${MEX_SUFFIX}]")
INCLUDE_DIRECTORIES(${MATLAB_ROOT}/extern/include)
LINK_DIRECTORIES(${MATLAB_ROOT}/bin/${MEX_PLATFORM})


MACRO(ADD_MEX_TARGET target)
  ADD_LIBRARY(${target} SHARED ${ARGN})
  TARGET_LINK_LIBRARIES(${target} mx mex)
  SET_TARGET_PROPERTIES(${target} PROPERTIES 
                        PREFIX "" 
                        SUFFIX ".${MEX_SUFFIX}"
#                        COMPILE_FLAGS "${MEX_CXX_FLAGS}"
#                        DEFINE_SYMBOL "${MEX_DEFINES} ${DEFINE_SYMBOL}"
#                        LINK_FLAGS "${MEX_RPATH} ${MEX_LDFLAGS} ${LINK_FLAGS}"
                        )
ENDMACRO(ADD_MEX_TARGET name)
